### ISSUE TITLE
Problem Installing on Mac OSX 10.10.5 (Yosemite)

### ISSUE THREAD

**Issue by tsalada** [jaffa4/pathutil#3]
$ panda install Path::Util
==> Fetching Path::Util
==> Building Path::Util
==> Testing Path::Util
Use of Nil in string context  in method new at /Users/jpolanik/Documents/myPerl6/.panda-work/1453415242_1/lib/Path/Util.pm line 53
Use of Nil in string context  in method new at /Users/jpolanik/Documents/myPerl6/.panda-work/1453415242_1/lib/Path/Util.pm line 53
# Failed test 'basename1'
# at t/all.t line 11

Use of Nil in string context  in method new at /Users/jpolanik/Documents/myPerl6/.panda-work/1453415242_1/lib/Path/Util.pm line 53
# Failed test 'basename2'
# at t/all.t line 13
# Failed test 'basename3'
# at t/all.t line 14

Use of Nil in string context  in method new at /Users/jpolanik/Documents/myPerl6/.panda-work/1453415242_1/lib/Path/Util.pm line 53
# Failed test 'justname1'
# at t/all.t line 16
# Failed test 'justname2'
# at t/all.t line 17

Use of Nil in string context  in method new at /Users/jpolanik/Documents/myPerl6/.panda-work/1453415242_1/lib/Path/Util.pm line 53
# Failed test 'extension1'
# at t/all.t line 19

Use of Nil in string context  in method getext at /Users/jpolanik/Documents/myPerl6/.panda-work/1453415242_1/lib/Path/Util.pm line 159
# Failed test 'extension2'
# at t/all.t line 20

Use of Nil in string context  in method new at /Users/jpolanik/Documents/myPerl6/.panda-work/1453415242_1/lib/Path/Util.pm line 53
# Failed test 'getdir'
# at t/all.t line 22

Use of Nil in string context  in method new at /Users/jpolanik/Documents/myPerl6/.panda-work/1453415242_1/lib/Path/Util.pm line 53
Use of Nil in string context  in method new at /Users/jpolanik/Documents/myPerl6/.panda-work/1453415242_1/lib/Path/Util.pm line 53
Use of Nil in string context  in method new at /Users/jpolanik/Documents/myPerl6/.panda-work/1453415242_1/lib/Path/Util.pm line 53
Use of Nil in string context  in method new at /Users/jpolanik/Documents/myPerl6/.panda-work/1453415242_1/lib/Path/Util.pm line 53
Dynamic variable $*OS not found
  in method fsseparator at /Users/jpolanik/Documents/myPerl6/.panda-work/1453415242_1/lib/Path/Util.pm line 289
  in block <unit> at t/all.t line 33

Actually thrown at:
  in method fsseparator at /Users/jpolanik/Documents/myPerl6/.panda-work/1453415242_1/lib/Path/Util.pm line 289
  in block <unit> at t/all.t line 33

t/all.t .. 
Dubious, test returned 8 (wstat 2048, 0x800)
Failed 8/18 subtests 
## Test Summary Report

t/all.t (Wstat: 2048 Tests: 18 Failed: 8)
  Failed tests:  2-9
  Non-zero exit status: 8
  Parse errors: No plan found in TAP output
Files=1, Tests=18,  2 wallclock secs ( 0.02 usr  0.01 sys +  2.27 cusr  0.12 csys =  2.42 CPU)
Result: FAIL
test stage failed for Path::Util: Tests failed
  in method install at /Users/jpolanik/.rakudobrew/moar-nom/install/share/perl6/site/sources/9036849E1656E91211D00AB4530B81D29A7D6E82 line 156
  in method resolve at /Users/jpolanik/.rakudobrew/moar-nom/install/share/perl6/site/sources/9036849E1656E91211D00AB4530B81D29A7D6E82 line 233
  in sub MAIN at /Users/jpolanik/.rakudobrew/moar-nom/install/share/perl6/site/resources/76CD539C815A33F2891D2EF3D6D96B1081567AD1 line 18
  in block <unit> at /Users/jpolanik/.rakudobrew/moar-nom/install/share/perl6/site/resources/76CD539C815A33F2891D2EF3D6D96B1081567AD1 line 150
## Failure Summary

Path::Util(
    *test stage failed for Path::Util: Tests failed)

**Comment by jaffa4** [comment]
I fixed this it. Try it now and see if it works for you well.

**Comment by tsalada** [comment]
No change.
Note: The problem seems to be in Path/Util line 53. It looks like $/ is not being populated.
I created a test script as follows:

#!/usr/bin/env perl6
constant $sepreg = /(<[\\/]>)/;
my $filename = "c:\g\b.mp4";
if ($filename ~~ $sepreg) {
    say $/[0].Str;
}
else {
    say "No match";
}

The result is: Use of Nil in string context  in block <unit> at t_PathUtil_01.pl6 line 5
Conclusion: The filename matches the regex but $/ isn't populated. This may be an issue with the Regular Expression matcher rather than this particular module.

**Comment by tsalada** [comment]
Actually, the script mentioned in the previous note will return the expected results if $sepreg is made a lexical variable instead of a constant. I have no idea why that would be the case.

**Comment by jaffa4** [comment]
YOu know that you can report this a bug, right?

**Comment by tsalada** [comment]
Where would I report it as a bug?
Meanwhile, I would urge you to fix this module either by making $sepreg a lexical variable OR by removing the sigil in front of the constant name. Both those changes would give the correct result. (A constant doesn't need a sigil; and, having one sometimes makes a difference. That would be the bug, I think.)

**Comment by jaffa4** [comment]
Read http://rakudo.org/tickets/

**Comment by jaffa4** [comment]
Tests seems to work on Windows.. Reopen if it happens again.
